# Generated by Django 3.1.7 on 2021-04-02 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lead',
            field=ckeditor.fields.RichTextField(default='null', verbose_name='Entrada'),
        ),
    ]
