# Generated by Django 3.1.4 on 2021-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('content', models.CharField(max_length=150, verbose_name='Opinión')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Fotografía')),
                ('autor', models.CharField(max_length=40, verbose_name='Nombre del autor')),
                ('profesion_localidad', models.CharField(max_length=50, verbose_name='Profesión - localidad')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
