# Generated by Django 3.1.7 on 2021-04-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='imagen',
            field=models.ImageField(default='null', upload_to='images', verbose_name='Fotografía'),
        ),
    ]
