# Generated by Django 3.1.7 on 2021-04-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20210402_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Opinión', 'verbose_name_plural': 'Opiniones'},
        ),
    ]
